### ISSUE TITLE
[BUG] Spawn menu text is cut off with multiple lines

### ISSUE THREAD

**Issue by shadow7483147** [Stooberton/ACF-3#371] opened 2023-09-01 03:42 UTC
**Short Description**

When there's multiple lines of text to display, it will get cut off in the spawn menu.

**Branch and Version**

Git-master-5ce7b37

**Screenshots (Optional)**

![image](https://github.com/Stooberton/ACF-3/assets/3190007/cd953d00-d9cb-48e9-97f8-096d6601c65d)

**Additional Information (Optional)**

 This happens both in the main menu and in the context menu. My screen resolution is 1600x900, running -windowed -noborder.

**Comment by shadow7483147** [comment] 2023-09-02 01:24
In singleplayer and a local server it seems fine, but the bug occurs on a specific server, [Valen Sandbox](https://steamcommunity.com/groups/valensandbox).

When selecting from a dropdown box (eg. Autocannon to Cannon, or AP to HE), the text will try to refresh but doesn't fill in all of the space it needs. This persists until you disconnect from the server.

**Comment by thecraftianman** [comment] 2023-09-02 17:28
Owner of that server here

This bug was a server-specific thing and caused by an issue with a custom addon. It was not ACF's fault in any way and is fixed on there now, so this issue can safely be closed👍

**Closed** 2023-09-02 18:54 UTC
Labels: bug
