### ISSUE TITLE
[BUG] menu not showing ents properly

### ISSUE THREAD

**Issue by Sypher866** [Stooberton/ACF-3#171] opened 2021-03-19 20:56 UTC
Just loading in the acf server and opening the menu guives me this error every time, its been a couple days.
Just broken menu, specificaly entities like weapons , missiles, engine, ect..

server: GIT-dev-3b2bb2a
cient: ZIP-master-f61425d

Load in the server and open menu, acf go brrrrr.

![image](https://user-images.githubusercontent.com/80986497/111841220-0566ce80-88d4-11eb-8277-6a25eb5ad7d5.png)

![image](https://user-images.githubusercontent.com/80986497/111841237-0bf54600-88d4-11eb-8f82-33f9a50836e1.png)

![image](https://user-images.githubusercontent.com/80986497/111841250-10b9fa00-88d4-11eb-91b9-971e03b0a7ba.png)

**Comment by TwistedTail** [comment] 2021-03-19 20:59
Try updating the server to the latest version, there's some changes on 871f8e0 that should help deal with this. Also duplicate of #168.

**Closed** 2021-11-23 04:10 UTC
Labels: bug, duplicate, dev branch
