### ISSUE TITLE
[SUGGESTION] Buff engine power

### ISSUE THREAD

**Issue by Goodva** [Stooberton/ACF-3#110] opened 2020-08-21 15:06 UTC
After Fuel was made not optional to have and after fuel consumtion was increaced we were promised a buff to all engines due to lack of boost from the fuel. After almost 2 month it is not here.

**Comment by TwistedTail** [comment] 2020-08-30 22:57
Duplicate of #69.

**Closed by TwistedTail** 2020-08-30 22:57 UTC
Labels: duplicate, enhancement
