### ISSUE TITLE
[SUGGESTION] Set a limit on how many flare launchers you can have on a vehicle.

### ISSUE THREAD

**Issue by bluemetaknight** [Stooberton/ACF-3#139] opened 2020-10-31 22:20 UTC
With automatic flare spam becoming common, I am starting to see major performance impact on servers when several planes that have this feature are fighting. I would suggest adding a cap on how many flare launchers you can have on vehicles. I will say that if this is implemented, you will just get people using grenade launchers to spam flares in a similar fashion. Limiting grenade launchers as well would work, but I'm sure several people will complain about that.

**Comment by TwistedTail** [comment] 2020-10-31 22:22
Duplicate of #130. In my opinion, grenade launchers should not be capable of firing flares.

**Closed** 2020-11-01 01:49 UTC
Labels: enhancement
