### ISSUE TITLE
[BUG] Crash on creating clientside entities

### ISSUE THREAD

**Issue by Gunglazoid** [Stooberton/ACF-3#228] opened 2021-11-21 04:33 UTC
**Short Description**
Opening Entities or Fun Stuff in ACF Menu tool crashes client

**Branch and Version**
Master 5c0a83b
Linux 64bit + Chromium

**Console Error Logs**
```
-Lua Stack Traces-
==================
  Client
    0. LegacySetModel - [C]:-1
      1. SetModel - addons/acf-3/lua/acf/base/util/sh_util.lua:616
        2. CreateEntity - addons/acf-3/lua/acf/base/util/sh_util.lua:371
          3. GetModelData - addons/acf-3/lua/acf/base/util/sh_util.lua:385
            4. GetModelCenter - addons/acf-3/lua/acf/base/util/sh_util.lua:453
              5. UpdateModel - addons/acf-3/lua/vgui/acf_panel.lua:260
                6. AddModelPreview - addons/acf-3/lua/vgui/acf_panel.lua:306
                  7. Action - addons/acf-3/lua/acf/client/menu_items/fun_menu.lua:19
                    8. OnNodeSelected - addons/acf-3/lua/acf/client/spawn_menu.lua:222
                      9. OnNodeSelected - lua/vgui/dtree_node.lua:78
                        10. OnNodeSelected - lua/vgui/dtree_node.lua:78
                          11. OnNodeSelected - lua/vgui/dtree_node.lua:78
                            12. SetSelectedItem - lua/vgui/dtree.lua:95
                              13. OnNodeSelected - addons/acf-3/lua/acf/client/spawn_menu.lua:207
                                14. OnNodeSelected - lua/vgui/dtree_node.lua:78
                                  15. OnNodeSelected - lua/vgui/dtree_node.lua:78
                                    16. SetSelectedItem - lua/vgui/dtree.lua:95

  Server
    Lua Interface = NULL

  MenuSystem
    *Not in Lua call OR Lua has panicked*
```
If opening entities the following change:
```
7. Action - addons/acf-3/lua/acf/client/menu_items/weapons_menu.lua:150
  15. DoClick - addons/acf-3/lua/acf/client/spawn_menu.lua:153
    16. (null) - lua/vgui/dlabel.lua:237
```

**Comment by TwistedTail** [comment] 2021-11-30 22:36
Another user has also reported this exact similar crash from a Windows session, so it's something related to Clientside Entities in general.

**Comment by TwistedTail** [comment] 2022-01-16 22:42
@Gunglazoid You can now test all the changes done in the [linux-crash-fix branch](https://github.com/Stooberton/ACF-3/tree/linux-crash-fix). If everything works as intended, then we can merge said branch with master and close this issue.

**Comment by Gunglazoid** [comment] 2022-01-17 03:39
Opening categories in ACF Menu tool now works, everything spawns fine. Should be good to merge

**Comment by TwistedTail** [comment] 2022-01-17 03:40
Changes have been pushed to master, thanks for the report.

**Closed by TwistedTail** 2022-01-17 03:40 UTC
Labels: bug, high priority, clientside
