### ISSUE TITLE
[BUG] Scalable ammo crates crash server when touched

### ISSUE THREAD

**Issue by DynamX767** [Stooberton/ACF-3#86] opened 2020-07-25 04:42 UTC
**Short Description**

When you re-scale an already spawned scalable ammo crate there is a chance that it crashes the server when touched with the physgun

**Comment by CheezusChrust** [comment] 2020-07-25 16:53
Had this happen with multiple people on my server, unfortunately it seems to be every 1/1000 time because I haven't been able to intentionally recreate it. I have ruled out anything else that would be coincidentally crashing the server - all 4 times I've caught it happening, it was a player re-scaling an existing ammo crate and then grabbing it with the physgun. If I catch any console errors relating to this I'll post them.

**Comment by TwistedTail** [comment] 2020-07-25 18:46
I wonder if that is being caused by f8b01db. I could try rolling back those changes and see if this still happens.

**Comment by TwistedTail** [comment] 2020-07-31 08:43
Rolled back the clientside desync fix on acd0683, update and try to replicate the issue. Personally, I haven't been able to replicate this crash, so I can't confirm this will fix it.

**Comment by CheezusChrust** [comment] 2020-08-05 19:41
Haven't had any crashes reported due to this issue since acd0683 but of course it's so rare it may be a coincidence.

**Comment by TwistedTail** [comment] 2021-01-20 04:46
After several months, I was unable to replicate this issue so I assume it was a false positive. Closing.

**Closed by TwistedTail** 2021-01-20 04:46 UTC
Labels: bug, can't replicate, dev branch, help wanted, high priority, info needed
